version: "2"

networks:
  postgres-base-net:
    driver: bridge

services:

  backend:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - NODE_ENV=development
      - PORT=8080
    ports:
      - "8080:8080"
      # - "5432:5432"
    volumes:
      - ./:/usr/src/app
    command: npm run start
    depends_on:
      - db
    networks:                                                                                                                                                               
      - postgres-base-net

  db:
    image: postgres:14.1-alpine
    container_name: "postgres"
    restart: always
    # restart: on-failure
    environment:
      # - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=test
    ports:
      - "5432:5432"
    networks:                                                                                                                                                               
      - postgres-base-net
